Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    config.vm.network :private_network, ip: "192.168.0.10"
    config.vm.hostname = "stream-vagrant"
    config.vm.define "stream-vagrant"
    config.vm.provider :virtualbox do |vb|
        vb.name = "stream-vagrant"
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 1
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/playbook.yml"
        ansible.groups = {
          "stream" => ["stream-vagrant"],
          "sand:children" => ["stream"]
        }
        ansible.extra_vars = {
            ansible_python_interpreter: "auto"
        }
        ansible.vault_password_file = "../ansible/.vault_password.txt"
    end

    config.vm.provision :shell,
        :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Helsinki /etc/localtime",
        run: "once"
end
