---
# docker/tasks
- name: Check installed docker version
  shell:
    cmd: dpkg -l docker-ce |grep docker-ce |awk '{print $3}'
  register: installed_docker_version

- name: Check installed containerd.io version
  shell:
    cmd: dpkg -l containerd.io |grep containerd.io |awk '{print $3}'
  register: installed_containerdio_version

- block:
    - name: Unhold Docker
      dpkg_selections:
        name: "{{ item }}"
        selection: install
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Install Docker prerequisites
      apt:
        name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-docker
        state: latest

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        state: present

    - name: Add Docker stable repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name:
        - docker-ce={{ docker_version }}
        - docker-ce-cli={{ docker_version }}
        - containerd.io={{ containerdio_version }}
        state: present

    - name: Hold Docker to prevent upgrading
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  when:
    - docker_version != installed_docker_version.stdout or containerdio_version != installed_containerdio_version.stdout

- name: Log into GitLab registry
  community.docker.docker_login:
    registry_url: registry.gitlab.com/kanaliiga/stream-rtmp
    username: "{{ git_user }}"
    password: "{{ git_token }}"
